import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const mockedSupabase = vi.hoisted(() => ({
  from: vi.fn(),
  rpc: vi.fn(),
  storage: { from: vi.fn() },
}));

vi.mock("../supabase", () => ({ supabase: mockedSupabase }));

import {
  deleteOfferImage,
  ImageCleanupPendingError,
  listOfferImages,
  reorderOfferImages,
  retryOfferImageObjectCleanup,
  setOfferHeroImage,
  uploadOfferImage,
} from "./repository";

const offerId = "123e4567-e89b-12d3-a456-426614174000";
const uploadId = "987e6543-e21b-42d3-a456-426614174000";
const expectedPath = `offers/${offerId}/${uploadId}.jpeg`;
const validAlt = "Surfer na fali w Ericeirze";
const imageRow = {
  id: "223e4567-e89b-42d3-a456-426614174000",
  offer_id: offerId,
  storage_path: expectedPath,
  alt_text: validAlt,
  position: 0,
};

const createInsertQuery = (result: { data: unknown; error: unknown }) => {
  const query = {
    insert: vi.fn(),
    select: vi.fn(),
    single: vi.fn(),
  };
  query.insert.mockReturnValue(query);
  query.select.mockReturnValue(query);
  query.single.mockResolvedValue(result);
  return query;
};

const createQuery = (result: { data: unknown; error: unknown }) => {
  const query = Object.assign(Promise.resolve(result), {
    select: vi.fn(),
    eq: vi.fn(),
    neq: vi.fn(),
    order: vi.fn(),
    update: vi.fn(),
    delete: vi.fn(),
    maybeSingle: vi.fn(),
  });
  query.select.mockReturnValue(query);
  query.eq.mockReturnValue(query);
  query.neq.mockReturnValue(query);
  query.order.mockReturnValue(query);
  query.update.mockReturnValue(query);
  query.delete.mockReturnValue(query);
  query.maybeSingle.mockReturnValue(query);
  return query;
};

describe("offer image repository upload", () => {
  const storageUpload = vi.fn();
  const storageRemove = vi.fn();

  beforeEach(() => {
    vi.spyOn(globalThis.crypto, "randomUUID").mockReturnValue(uploadId);
    storageUpload.mockResolvedValue({ data: { path: expectedPath }, error: null });
    storageRemove.mockResolvedValue({ data: [], error: null });
    mockedSupabase.storage.from.mockReturnValue({
      upload: storageUpload,
      remove: storageRemove,
    });
  });

  afterEach(() => {
    vi.restoreAllMocks();
    vi.resetAllMocks();
  });

  it("uploads the generated object before inserting the gallery row", async () => {
    const insertQuery = createInsertQuery({ data: imageRow, error: null });
    mockedSupabase.from.mockReturnValue(insertQuery);
    const file = new File(["jpeg-data"], "../../sekretne-zdjecie.jpeg", {
      type: "image/jpeg",
    });

    await expect(uploadOfferImage(offerId, file, `  ${validAlt}  `, 0)).resolves.toEqual({
      id: imageRow.id,
      path: expectedPath,
      alt: validAlt,
      position: 0,
      signedUrl: null,
    });

    expect(storageUpload.mock.invocationCallOrder[0]).toBeLessThan(
      insertQuery.insert.mock.invocationCallOrder[0]!,
    );
    expect(storageUpload).toHaveBeenCalledWith(expectedPath, expect.any(Blob), {
      contentType: "image/jpeg",
      upsert: false,
    });
    expect(expectedPath).not.toContain(file.name);
    expect(insertQuery.insert).toHaveBeenCalledWith({
      offer_id: offerId,
      storage_path: expectedPath,
      alt_text: validAlt,
      position: 0,
    });
  });

  it("removes only the path generated by this call when row insertion fails", async () => {
    const databaseError = { code: "42501" };
    const insertQuery = createInsertQuery({ data: null, error: databaseError });
    mockedSupabase.from.mockReturnValue(insertQuery);
    const file = new File(["jpeg-data"], "prywatna-nazwa.jpeg", { type: "image/jpeg" });

    await expect(uploadOfferImage(offerId, file, validAlt, 0)).rejects.toMatchObject({
      name: "ImageRepositoryError",
      message: "Obraz został wgrany, ale nie udało się zapisać go w galerii.",
      cause: databaseError,
    });

    expect(storageRemove).toHaveBeenCalledWith([expectedPath]);
    expect(storageRemove).toHaveBeenCalledOnce();
  });

  it("logs only the generated path when compensating removal fails", async () => {
    const insertQuery = createInsertQuery({ data: null, error: { code: "42501" } });
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => undefined);
    mockedSupabase.from.mockReturnValue(insertQuery);
    storageRemove.mockResolvedValue({ data: null, error: { message: "storage failure" } });
    const file = new File(["jpeg-data"], "tajna-nazwa.jpeg", { type: "image/jpeg" });

    await expect(uploadOfferImage(offerId, file, validAlt, 0)).rejects.toMatchObject({
      name: "ImageRepositoryError",
      message: "Obraz został wgrany, ale nie udało się zapisać go w galerii.",
    });

    expect(consoleError).toHaveBeenCalledWith("image_upload_compensation_failed", {
      storagePath: expectedPath,
    });
    expect(JSON.stringify(consoleError.mock.calls)).not.toContain(file.name);
  });

  it("keeps compensation errors neutral when Storage removal rejects", async () => {
    const insertQuery = createInsertQuery({ data: null, error: { code: "42501" } });
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => undefined);
    mockedSupabase.from.mockReturnValue(insertQuery);
    storageRemove.mockRejectedValue(new Error("private network details"));

    await expect(
      uploadOfferImage(
        offerId,
        new File(["jpeg-data"], "nazwa-pliku.jpeg", { type: "image/jpeg" }),
        validAlt,
        0,
      ),
    ).rejects.toMatchObject({
      name: "ImageRepositoryError",
      message: "Obraz został wgrany, ale nie udało się zapisać go w galerii.",
    });
    expect(consoleError).toHaveBeenCalledWith("image_upload_compensation_failed", {
      storagePath: expectedPath,
    });
    expect(JSON.stringify(consoleError.mock.calls)).not.toContain("private network details");
  });

  it.each([" abcd ", ` ${"a".repeat(181)} `])(
    "rejects alt text outside the trimmed 5–180 character range before Storage",
    async (altText) => {
      const file = new File(["jpeg-data"], "fala.jpeg", { type: "image/jpeg" });

      await expect(uploadOfferImage(offerId, file, altText, 0)).rejects.toMatchObject({
        name: "ImageRepositoryError",
      });

      expect(mockedSupabase.storage.from).not.toHaveBeenCalled();
      expect(mockedSupabase.from).not.toHaveBeenCalled();
    },
  );

  it("rejects an invalid file, offer id, or position before Storage", async () => {
    const invalidFile = new File(["gif-data"], "fala.gif", { type: "image/gif" });
    const validFile = new File(["jpeg-data"], "fala.jpeg", { type: "image/jpeg" });

    await expect(uploadOfferImage(offerId, invalidFile, validAlt, 0)).rejects.toMatchObject({
      name: "ImageRepositoryError",
    });
    await expect(uploadOfferImage("invalid-id", validFile, validAlt, 0)).rejects.toMatchObject({
      name: "ImageRepositoryError",
    });
    await expect(uploadOfferImage(offerId, validFile, validAlt, -1)).rejects.toMatchObject({
      name: "ImageRepositoryError",
    });

    expect(mockedSupabase.storage.from).not.toHaveBeenCalled();
    expect(mockedSupabase.from).not.toHaveBeenCalled();
  });

  it("does not insert or remove anything when Storage upload fails", async () => {
    const storageError = { message: "upload rejected" };
    storageUpload.mockResolvedValue({ data: null, error: storageError });
    const file = new File(["jpeg-data"], "fala.jpeg", { type: "image/jpeg" });

    await expect(uploadOfferImage(offerId, file, validAlt, 0)).rejects.toMatchObject({
      name: "ImageRepositoryError",
      message: "Nie udało się wgrać obrazu.",
      cause: storageError,
    });

    expect(mockedSupabase.from).not.toHaveBeenCalled();
    expect(storageRemove).not.toHaveBeenCalled();
  });
});

describe("offer image repository lifecycle", () => {
  const secondImageRow = {
    id: "323e4567-e89b-42d3-a456-426614174000",
    offer_id: offerId,
    storage_path: `offers/${offerId}/423e4567-e89b-42d3-a456-426614174000.webp`,
    alt_text: "Drugi surfer na spokojnej fali",
    position: 1,
  };

  afterEach(() => {
    vi.restoreAllMocks();
    vi.resetAllMocks();
  });

  it("lists validated images in database order with administrator signed URLs", async () => {
    const listQuery = createQuery({ data: [imageRow, secondImageRow], error: null });
    mockedSupabase.from.mockReturnValue(listQuery);
    const createSignedUrls = vi.fn().mockResolvedValue({
      data: [
        { path: imageRow.storage_path, signedUrl: "https://signed.example/first.jpeg" },
        { path: secondImageRow.storage_path, signedUrl: "https://signed.example/second.webp" },
      ],
      error: null,
    });
    mockedSupabase.storage.from.mockReturnValue({ createSignedUrls });

    await expect(listOfferImages(offerId)).resolves.toEqual([
      {
        id: imageRow.id,
        path: imageRow.storage_path,
        alt: imageRow.alt_text,
        position: 0,
        signedUrl: "https://signed.example/first.jpeg",
      },
      {
        id: secondImageRow.id,
        path: secondImageRow.storage_path,
        alt: secondImageRow.alt_text,
        position: 1,
        signedUrl: "https://signed.example/second.webp",
      },
    ]);
    expect(listQuery.eq).toHaveBeenCalledWith("offer_id", offerId);
    expect(listQuery.order).toHaveBeenCalledWith("position", { ascending: true });
    expect(createSignedUrls).toHaveBeenCalledWith(
      [imageRow.storage_path, secondImageRow.storage_path],
      3600,
    );
  });

  it("sets a hero only from an image row belonging to the same offer", async () => {
    const imageQuery = createQuery({ data: imageRow, error: null });
    const offerUpdate = createQuery({ data: null, error: null });
    mockedSupabase.from.mockReturnValueOnce(imageQuery).mockReturnValueOnce(offerUpdate);

    await expect(setOfferHeroImage(offerId, imageRow.id)).resolves.toBeUndefined();

    expect(imageQuery.eq).toHaveBeenCalledWith("id", imageRow.id);
    expect(imageQuery.eq).toHaveBeenCalledWith("offer_id", offerId);
    expect(offerUpdate.update).toHaveBeenCalledWith({ hero_image: imageRow.storage_path });
    expect(offerUpdate.eq).toHaveBeenCalledWith("id", offerId);
    expect(offerUpdate.delete).not.toHaveBeenCalled();
  });

  it("never deletes a hero row or removes its object", async () => {
    const storageRemove = vi.fn();
    mockedSupabase.storage.from.mockReturnValue({ remove: storageRemove });
    const imageQuery = createQuery({ data: imageRow, error: null });
    const heroReferences = createQuery({ data: [{ id: offerId }], error: null });
    mockedSupabase.from.mockReturnValueOnce(imageQuery).mockReturnValueOnce(heroReferences);

    await expect(deleteOfferImage(imageRow.id)).rejects.toThrow("Nie można usunąć obrazu głównego");

    expect(storageRemove).not.toHaveBeenCalled();
    expect(heroReferences.eq).toHaveBeenCalledWith("hero_image", imageRow.storage_path);
  });

  it("rechecks references and keeps the object when a concurrent reference appears", async () => {
    const storageRemove = vi.fn();
    mockedSupabase.storage.from.mockReturnValue({ remove: storageRemove });
    const imageQuery = createQuery({ data: imageRow, error: null });
    const initialHeroReferences = createQuery({ data: [], error: null });
    const initialImageReferences = createQuery({ data: [], error: null });
    const deleteQuery = createQuery({ data: null, error: null });
    const finalHeroReferences = createQuery({ data: [], error: null });
    const finalImageReferences = createQuery({ data: [{ id: secondImageRow.id }], error: null });
    mockedSupabase.from
      .mockReturnValueOnce(imageQuery)
      .mockReturnValueOnce(initialHeroReferences)
      .mockReturnValueOnce(initialImageReferences)
      .mockReturnValueOnce(deleteQuery)
      .mockReturnValueOnce(finalHeroReferences)
      .mockReturnValueOnce(finalImageReferences);

    await expect(deleteOfferImage(imageRow.id)).resolves.toBeUndefined();

    expect(deleteQuery.delete).toHaveBeenCalledOnce();
    expect(deleteQuery.eq).toHaveBeenCalledWith("id", imageRow.id);
    expect(storageRemove).not.toHaveBeenCalled();
  });

  it("reports cleanup-pending state with only the retry path after deleting the row", async () => {
    const storageRemove = vi.fn().mockResolvedValue({
      data: null,
      error: { message: "private storage details" },
    });
    mockedSupabase.storage.from.mockReturnValue({ remove: storageRemove });
    const consoleError = vi.spyOn(console, "error").mockImplementation(() => undefined);
    mockedSupabase.from
      .mockReturnValueOnce(createQuery({ data: imageRow, error: null }))
      .mockReturnValueOnce(createQuery({ data: [], error: null }))
      .mockReturnValueOnce(createQuery({ data: [], error: null }))
      .mockReturnValueOnce(createQuery({ data: null, error: null }))
      .mockReturnValueOnce(createQuery({ data: [], error: null }))
      .mockReturnValueOnce(createQuery({ data: [], error: null }));

    const error = await deleteOfferImage(imageRow.id).catch((caught: unknown) => caught);

    expect(error).toBeInstanceOf(ImageCleanupPendingError);
    expect(error).toMatchObject({ storagePath: imageRow.storage_path });
    expect(error).not.toHaveProperty("imageId");
    expect(error).not.toHaveProperty("cause");
    expect(consoleError).toHaveBeenCalledWith("offer_image_cleanup_failed", {
      imageId: imageRow.id,
      storagePath: imageRow.storage_path,
    });
    expect(JSON.stringify(consoleError.mock.calls)).not.toContain("private storage details");
    expect(JSON.stringify(consoleError.mock.calls)).not.toContain("signedUrl");
  });

  it("retries object cleanup only after both reference checks are clear", async () => {
    const storageRemove = vi.fn().mockResolvedValue({ data: [], error: null });
    mockedSupabase.storage.from.mockReturnValue({ remove: storageRemove });
    const heroReferences = createQuery({ data: [], error: null });
    const imageReferences = createQuery({ data: [], error: null });
    mockedSupabase.from.mockReturnValueOnce(heroReferences).mockReturnValueOnce(imageReferences);

    await expect(retryOfferImageObjectCleanup(imageRow.storage_path)).resolves.toBeUndefined();

    expect(heroReferences.eq).toHaveBeenCalledWith("hero_image", imageRow.storage_path);
    expect(imageReferences.eq).toHaveBeenCalledWith("storage_path", imageRow.storage_path);
    expect(storageRemove).toHaveBeenCalledWith([imageRow.storage_path]);
  });

  it("does not retry removal for an invalid or still-referenced path", async () => {
    const storageRemove = vi.fn();
    mockedSupabase.storage.from.mockReturnValue({ remove: storageRemove });

    await expect(retryOfferImageObjectCleanup("other-bucket/object.jpeg")).rejects.toMatchObject({
      name: "ImageRepositoryError",
    });
    expect(mockedSupabase.from).not.toHaveBeenCalled();

    mockedSupabase.from.mockReturnValueOnce(createQuery({ data: [{ id: offerId }], error: null }));
    await expect(retryOfferImageObjectCleanup(imageRow.storage_path)).resolves.toBeUndefined();
    expect(storageRemove).not.toHaveBeenCalled();
  });

  it("reorders the complete image permutation through one atomic database call", async () => {
    mockedSupabase.rpc.mockResolvedValue({ data: null, error: null });

    await expect(
      reorderOfferImages(offerId, [secondImageRow.id, imageRow.id]),
    ).resolves.toBeUndefined();

    expect(mockedSupabase.rpc).toHaveBeenCalledOnce();
    expect(mockedSupabase.rpc).toHaveBeenCalledWith("reorder_offer_images", {
      p_offer_id: offerId,
      p_ordered_image_ids: [secondImageRow.id, imageRow.id],
    });
    expect(mockedSupabase.from).not.toHaveBeenCalled();
  });

  it("rejects malformed reorder identifiers before contacting the database", async () => {
    mockedSupabase.rpc.mockResolvedValue({ data: null, error: null });

    await expect(reorderOfferImages("invalid-offer", [imageRow.id])).rejects.toMatchObject({
      name: "ImageRepositoryError",
    });
    await expect(reorderOfferImages(offerId, [imageRow.id, imageRow.id])).rejects.toMatchObject({
      name: "ImageRepositoryError",
    });

    expect(mockedSupabase.rpc).not.toHaveBeenCalled();
  });

  it("reports an atomic reorder rejection without issuing follow-up mutations", async () => {
    mockedSupabase.rpc.mockResolvedValue({ data: null, error: { code: "22023" } });

    await expect(
      reorderOfferImages(offerId, [secondImageRow.id, imageRow.id]),
    ).rejects.toMatchObject({
      name: "ImageRepositoryError",
      message: "Nie udało się zmienić kolejności obrazów.",
    });

    expect(mockedSupabase.rpc).toHaveBeenCalledOnce();
    expect(mockedSupabase.from).not.toHaveBeenCalled();
  });
});
