/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSlugRouteImport } from './routes/admin.$slug'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/admin/$slug',
  path: '/admin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/$slug': typeof AdminSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/$slug' | '/trips/$slug' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/$slug' | '/trips/$slug' | '/admin'
  id: '__root__' | '/' | '/admin/$slug' | '/trips/$slug' | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminSlugRoute: typeof AdminSlugRoute
  TripsSlugRoute: typeof TripsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$slug': {
      id: '/admin/$slug'
      path: '/admin/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminSlugRoute: AdminSlugRoute,
  TripsSlugRoute: TripsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
