/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventyRouteImport } from './routes/eventy'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ONasRouteImport } from './routes/o-nas'
import { Route as PolkolonieRouteImport } from './routes/polkolonie'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSlugRouteImport } from './routes/admin.$slug'
import { Route as AdminDokumentyRouteImport } from './routes/admin.dokumenty'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as PolkolonieSlugRouteImport } from './routes/polkolonie.$slug'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'
import { Route as WyjazdyIndexRouteImport } from './routes/wyjazdy.index'
import { Route as WyjazdySlugRouteImport } from './routes/wyjazdy.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventyRoute = EventyRouteImport.update({
  id: '/eventy',
  path: '/eventy',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ONasRoute = ONasRouteImport.update({
  id: '/o-nas',
  path: '/o-nas',
  getParentRoute: () => rootRouteImport,
} as any)
const PolkolonieRoute = PolkolonieRouteImport.update({
  id: '/polkolonie',
  path: '/polkolonie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSlugRoute = AdminSlugRouteImport.update({
  id: '/admin/$slug',
  path: '/admin/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDokumentyRoute = AdminDokumentyRouteImport.update({
  id: '/admin/dokumenty',
  path: '/admin/dokumenty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PolkolonieSlugRoute = PolkolonieSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PolkolonieRoute,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WyjazdyIndexRoute = WyjazdyIndexRouteImport.update({
  id: '/wyjazdy/',
  path: '/wyjazdy/',
  getParentRoute: () => rootRouteImport,
} as any)
const WyjazdySlugRoute = WyjazdySlugRouteImport.update({
  id: '/wyjazdy/$slug',
  path: '/wyjazdy/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eventy': typeof EventyRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/polkolonie': typeof PolkolonieRouteWithChildren
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/dokumenty': typeof AdminDokumentyRoute
  '/admin/login': typeof AdminLoginRoute
  '/polkolonie/$slug': typeof PolkolonieSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/wyjazdy/$slug': typeof WyjazdySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/wyjazdy/': typeof WyjazdyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eventy': typeof EventyRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/polkolonie': typeof PolkolonieRouteWithChildren
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/dokumenty': typeof AdminDokumentyRoute
  '/admin/login': typeof AdminLoginRoute
  '/polkolonie/$slug': typeof PolkolonieSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/wyjazdy/$slug': typeof WyjazdySlugRoute
  '/admin': typeof AdminIndexRoute
  '/wyjazdy': typeof WyjazdyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eventy': typeof EventyRoute
  '/kontakt': typeof KontaktRoute
  '/o-nas': typeof ONasRoute
  '/polkolonie': typeof PolkolonieRouteWithChildren
  '/admin/$slug': typeof AdminSlugRoute
  '/admin/dokumenty': typeof AdminDokumentyRoute
  '/admin/login': typeof AdminLoginRoute
  '/polkolonie/$slug': typeof PolkolonieSlugRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/wyjazdy/$slug': typeof WyjazdySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/wyjazdy/': typeof WyjazdyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eventy'
    | '/kontakt'
    | '/o-nas'
    | '/polkolonie'
    | '/admin/$slug'
    | '/admin/dokumenty'
    | '/admin/login'
    | '/polkolonie/$slug'
    | '/trips/$slug'
    | '/wyjazdy/$slug'
    | '/admin/'
    | '/wyjazdy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/eventy'
    | '/kontakt'
    | '/o-nas'
    | '/polkolonie'
    | '/admin/$slug'
    | '/admin/dokumenty'
    | '/admin/login'
    | '/polkolonie/$slug'
    | '/trips/$slug'
    | '/wyjazdy/$slug'
    | '/admin'
    | '/wyjazdy'
  id:
    | '__root__'
    | '/'
    | '/eventy'
    | '/kontakt'
    | '/o-nas'
    | '/polkolonie'
    | '/admin/$slug'
    | '/admin/dokumenty'
    | '/admin/login'
    | '/polkolonie/$slug'
    | '/trips/$slug'
    | '/wyjazdy/$slug'
    | '/admin/'
    | '/wyjazdy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventyRoute: typeof EventyRoute
  KontaktRoute: typeof KontaktRoute
  ONasRoute: typeof ONasRoute
  PolkolonieRoute: typeof PolkolonieRouteWithChildren
  AdminSlugRoute: typeof AdminSlugRoute
  AdminDokumentyRoute: typeof AdminDokumentyRoute
  AdminLoginRoute: typeof AdminLoginRoute
  TripsSlugRoute: typeof TripsSlugRoute
  WyjazdySlugRoute: typeof WyjazdySlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  WyjazdyIndexRoute: typeof WyjazdyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventy': {
      id: '/eventy'
      path: '/eventy'
      fullPath: '/eventy'
      preLoaderRoute: typeof EventyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-nas': {
      id: '/o-nas'
      path: '/o-nas'
      fullPath: '/o-nas'
      preLoaderRoute: typeof ONasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polkolonie': {
      id: '/polkolonie'
      path: '/polkolonie'
      fullPath: '/polkolonie'
      preLoaderRoute: typeof PolkolonieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$slug': {
      id: '/admin/$slug'
      path: '/admin/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AdminSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dokumenty': {
      id: '/admin/dokumenty'
      path: '/admin/dokumenty'
      fullPath: '/admin/dokumenty'
      preLoaderRoute: typeof AdminDokumentyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polkolonie/$slug': {
      id: '/polkolonie/$slug'
      path: '/$slug'
      fullPath: '/polkolonie/$slug'
      preLoaderRoute: typeof PolkolonieSlugRouteImport
      parentRoute: typeof PolkolonieRoute
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wyjazdy/': {
      id: '/wyjazdy/'
      path: '/wyjazdy'
      fullPath: '/wyjazdy/'
      preLoaderRoute: typeof WyjazdyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wyjazdy/$slug': {
      id: '/wyjazdy/$slug'
      path: '/wyjazdy/$slug'
      fullPath: '/wyjazdy/$slug'
      preLoaderRoute: typeof WyjazdySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PolkolonieRouteChildren {
  PolkolonieSlugRoute: typeof PolkolonieSlugRoute
}

const PolkolonieRouteChildren: PolkolonieRouteChildren = {
  PolkolonieSlugRoute: PolkolonieSlugRoute,
}

const PolkolonieRouteWithChildren = PolkolonieRoute._addFileChildren(
  PolkolonieRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventyRoute: EventyRoute,
  KontaktRoute: KontaktRoute,
  ONasRoute: ONasRoute,
  PolkolonieRoute: PolkolonieRouteWithChildren,
  AdminSlugRoute: AdminSlugRoute,
  AdminDokumentyRoute: AdminDokumentyRoute,
  AdminLoginRoute: AdminLoginRoute,
  TripsSlugRoute: TripsSlugRoute,
  WyjazdySlugRoute: WyjazdySlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  WyjazdyIndexRoute: WyjazdyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
